version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 19...
      - curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash - &&\
      - sudo apt-get install -y nodejs
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building...
      - npm run dev
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: public
