name: CI

# 1
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  pull_request:
    branches: [ "master" ]
    paths: 
      - ".github/**"

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - name: Build
          env:
              NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
              NETLIFY_SITE_ID: ${{ secrets.NETLIFY_ID }}
          run:
            sudo apt -y install vite
            npm run build
            npm install netlify-cli -g
            netlify deploy
